import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as THREE from 'three';
import {connectionFrame,createConnectionWood} from '../src/channel-geometry.js';
function cast(geometries,origin,direction){const material=new THREE.MeshBasicMaterial({side:THREE.DoubleSide});const group=new THREE.Group();for(const g of geometries)group.add(new THREE.Mesh(g,material));group.updateMatrixWorld(true);const ray=new THREE.Raycaster(new THREE.Vector3(...origin),new THREE.Vector3(...direction));const hit=ray.intersectObject(group)[0];material.dispose();return hit?.point;}
const near=(a,b)=>assert.ok(Math.abs(a-b)<.001,`${a} should equal ${b}`);
test('the two CAD dowels fit the illustrated bores and the connector is not a substitute model',async()=>{const source=JSON.parse(await readFile('public/assets/e3259bm-mesh.json','utf8'));assert.equal(source.sku,'E3259BM');assert.equal(source.sha256,'838051f7d26acb8e08706cb9b4942ac34579ac58a99cc16e2aaf9e7c069274de');assert.equal(source.positions.length,source.normals.length);assert.ok(source.indices.length>1500);const {carrier}=createConnectionWood(THREE);for(const x of [-16,16]){near(cast(carrier,[x,-1,0],[0,1,0]).y,22);}near(cast(carrier,[0,-1,0],[0,1,0]).y,0);carrier.forEach(g=>g.dispose());});
test('channel has a recessed entry and solid retaining lips over the wider pocket',()=>{const {carrier,receiver}=createConnectionWood(THREE);near(cast(receiver,[0,10,0],[0,-1,0]).y,-9.1);near(cast(receiver,[-40,10,0],[0,-1,0]).y,-9.1);near(cast(receiver,[-40,10,2.8],[0,-1,0]).y,0);near(cast(receiver,[-40,-6,2.8],[0,1,0]).y,-3.65);[...carrier,...receiver].forEach(g=>g.dispose());});
test('mount, seat, slide and cabinet happen in order with the fitting rigidly attached after mounting',()=>{const first=connectionFrame(0);assert.equal(first.woodOpacity,0);assert.equal(first.receiverOpacity,0);assert.equal(first.growth,0);const mount=connectionFrame(4.4);near(mount.connectorY,0);assert.equal(mount.carrierY,45);const seat=connectionFrame(8.4);near(seat.carrierY,0);near(seat.carrierX,0);const locked=connectionFrame(10.7);near(locked.carrierX,-31);near(locked.carrierY,0);near(locked.connectorY,0);assert.equal(locked.growth,0);assert.equal(connectionFrame(16).growth,1);for(let t=4.4;t<=16;t+=.1)near(connectionFrame(t).connectorY,0);for(let t=0;t<=16;t+=.05){const f=connectionFrame(t);assert.ok(Object.values(f).every(v=>typeof v==='boolean'||Number.isFinite(v)));}});
