import {calculateSavings} from './calculator.js';
const $ = (s,root=document)=>root.querySelector(s);
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let motionPaused=reduced.matches;
try { motionPaused=motionPaused || sessionStorage.getItem('lockdowel-motion')==='paused'; } catch {}
function setMotion(value){motionPaused=value;document.documentElement.classList.toggle('motion-paused',value);$$('[data-motion]').forEach(b=>{b.textContent=value?'Resume motion':'Pause motion';b.setAttribute('aria-pressed',String(value));});window.dispatchEvent(new CustomEvent('studio-motion',{detail:{paused:value}}));}
setMotion(motionPaused);
$('[data-motion]')?.addEventListener('click',()=>{setMotion(!motionPaused);try{sessionStorage.setItem('lockdowel-motion',motionPaused?'paused':'playing');}catch{}});
reduced.addEventListener('change',e=>{if(e.matches)setMotion(true);});
const menu=$('.menu-toggle');
function closeMenu(){menu?.setAttribute('aria-expanded','false');$('#main-nav')?.classList.remove('is-open');}
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('#main-nav').classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeMenu();});
if('IntersectionObserver' in window && !reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{threshold:.06});document.documentElement.classList.add('js-reveal');$$('.reveal').forEach(el=>observer.observe(el));}
$$('[data-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('.drawing-card').forEach(card=>{card.hidden=button.dataset.filter!=='All'&&card.dataset.kind!==button.dataset.filter;});}));
const applications={
 furniture:{title:'Let the design<br>do the talking.',label:'FURNITURE / BUILT AROUND YOUR IDEA',description:'Explore concealed connections for tables, casegoods and other furniture. Start with access, assembly direction and the material your design uses.',image:'furniture.jpg',alt:'Furniture application from Lockdowel’s main website',questions:['Where can each part approach and slide?','Will the finished piece need to come apart?','What material and panel thickness are you using?'],url:'/drawings/boat-table/',link:'Next: explore a furniture study'},
 cabinetry:{title:'Bring the whole<br>cabinet together.',label:'CABINETRY / CONSIDER THE COMPLETE ASSEMBLY',description:'Look at the cabinet as a system: sides, shelves, back, and the order they come together. A representative sample helps reveal what works in your shop.',image:'cabinetry.jpg',alt:'Finished kitchen cabinetry from Lockdowel’s main website',questions:['Which parts carry the connectors and which receive them?','Can every connection be reached in your assembly sequence?','How will you validate the machining in your panel material?'],url:'/drawings/open-cubby/',link:'Next: explore a cabinetry study'},
 panels:{title:'A clean finish.<br>A considered connection.',label:'WALL PANELS / DESIGN BEYOND THE SURFACE',description:'Explore how concealed fastening can support an uncluttered architectural finish. The substrate, access and requirements of the installation guide the choice of system.',image:'wall-panels.png',alt:'Architectural wall panel application from Lockdowel’s main website',questions:['What is the panel material and supporting substrate?','Does the application need a removable or permanent connection?','What loads and installation conditions must be reviewed?'],url:'/start-project/',link:'Next: plan your wall panel project'}
};
function selectApplication(button){const key=button.dataset.application;const a=applications[key];$$('[data-application]').forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1;});$('#application-panel').setAttribute('aria-labelledby',button.id);$('#application-title').innerHTML=a.title;$('#application-label').textContent=a.label;$('#application-description').textContent=a.description;$('#application-image').src='/assets/'+a.image;$('#application-image').alt=a.alt;$('#application-questions').replaceChildren(...a.questions.map(q=>{const li=document.createElement('li');li.textContent=q;return li;}));$('#application-link').href=a.url;$('#application-link').innerHTML=a.link+' <span aria-hidden="true">↗</span>';}
$$('[data-application]').forEach((button,index)=>{button.addEventListener('click',()=>selectApplication(button));button.addEventListener('keydown',e=>{const tabs=$$('[data-application]');let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectApplication(tabs[next]);tabs[next].focus();}});});
const video=$('#howto-video');
if(video){$('[data-video-back]').addEventListener('click',()=>{video.currentTime=Math.max(0,video.currentTime-5);});$('[data-video-speed]').addEventListener('click',e=>{const slow=video.playbackRate!==.5;video.playbackRate=slow?.5:1;e.currentTarget.setAttribute('aria-pressed',String(slow));e.currentTarget.textContent=slow?'1× normal speed':'0.5× slow motion';});$('[data-video-restart]').addEventListener('click',()=>{video.currentTime=0;video.play().catch(()=>{});});}
$('[data-copy-link]')?.addEventListener('click',async()=>{const toast=$('.toast');try{await navigator.clipboard.writeText(location.href);toast.textContent='Page link copied. This local URL works only on this computer.';}catch{toast.textContent='Copy this page’s address from your browser to save the local link.';}setTimeout(()=>{toast.textContent='';},6500);});
const form=$('#savings-form');
if(form){let latest=null;const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});const decimal=new Intl.NumberFormat('en-US',{maximumFractionDigits:1});const read=()=>Object.fromEntries(['units','before','after','rate'].map(name=>[name,form.elements[name].value.trim()===''?NaN:Number(form.elements[name].value)]));function update(){const values=read();const result=form.checkValidity()?calculateSavings(values):null;latest=result?{...values,...result}:null;$('[data-export-savings]').disabled=!result;if(!result){$('#savings-money').textContent='—';$('#savings-hours').textContent='—';$('#savings-percent').textContent='—';$('#calculator-error').textContent='Enter valid, nonnegative values in all four fields.';$('#savings-direction').textContent='Complete your scenario to see the estimate.';return;}$('#calculator-error').textContent='';$('#savings-money').textContent=money.format(result.money);$('#savings-hours').textContent=decimal.format(result.hours);$('#savings-percent').textContent=result.percent===null?'N/A':decimal.format(result.percent)+'%';$('#savings-direction').textContent=result.money>0?'Less assembly labor in this scenario.':result.money<0?'Additional assembly labor in this scenario.':'No assembly labor cost difference in this scenario.';const max=Math.max(values.before,values.after,1);$('#bar-before').style.width=(values.before/max*78)+'%';$('#bar-after').style.width=(values.after/max*78)+'%';}form.addEventListener('input',update);form.addEventListener('submit',e=>e.preventDefault());update();$('[data-export-savings]').addEventListener('click',()=>{if(!latest)return;const s=latest;const content=`Lockdowel Build — assembly labor scenario\n\nUnits/month: ${s.units}\nCurrent minutes/unit: ${s.before}\nTrial minutes/unit: ${s.after}\nLoaded labor rate (USD/hour): ${s.rate}\nMonthly hours difference: ${s.hours.toFixed(2)}\nMonthly labor cost difference (USD): ${s.money.toFixed(2)}\nCycle time reduction: ${s.percent===null?'N/A':s.percent.toFixed(2)+'%'}\n\nFormula: units × (current minutes − trial minutes) ÷ 60 × labor rate.\nNegative values mean additional time or cost.\nScenario only; excludes hardware, machining, equipment, training, shipping and other costs. Validate using measured trials.\n`;const blob=new Blob([content],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='lockdowel-assembly-scenario.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
if($('[data-scene]')){import('./scene.js').then(({initScene})=>$$('[data-scene]').forEach(el=>initScene(el,{paused:motionPaused}))).catch(()=>{$$('[data-scene]').forEach(el=>{$('.live-indicator',el).textContent='DRAWING PREVIEW';$$('button',el).forEach(b=>b.disabled=true);$('.scene-hint',el).textContent='3D UNAVAILABLE';});});}

$$('[data-sheet]').forEach(button=>button.addEventListener('click',()=>{const preview=button.closest('.study-preview');$('img',preview).src=button.dataset.sheet;$$('[data-sheet]',preview).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
// The homepage connector scene is independent of customer project assets.
const channelRoot=document.querySelector('[data-channel-home]');
if(channelRoot)import('./channel-home.js').then(({initChannelHome})=>initChannelHome(channelRoot,{paused:motionPaused})).catch(()=>{channelRoot.querySelector('.connection-stage').classList.add('is-fallback');channelRoot.querySelector('.connection-loading')?.remove();channelRoot.querySelector('[data-channel-status]').textContent='WATCH THE ORIGINAL FILM';channelRoot.querySelector('.connection-fallback-link').hidden=false;channelRoot.querySelectorAll('button,input').forEach(b=>b.disabled=true);});
