export const guides = [
 {
  slug:'how-channel-lock-connectors-work',category:'Connection fundamentals',title:'How channel-lock connectors work',description:'Understand the mounting panel, receiving channel, and align-seat-slide movement before planning a Lockdowel joint.',summary:'Follow the two sides of a channel-lock joint, from the mounted fitting to the receiving channel.',image:'e3259bm-preview.png',imageAlt:'E3259BM connector presentation model',reading:'4 minute read',
  sections:[
   {id:'two-sides',title:'Start with the two sides of the joint',html:`<p>A channel-lock connection brings together a fitting mounted to one panel and a routed receiving feature in the mating panel. Lockdowel describes keyhole slots and a sliding engagement in its product overview. Understanding which panel carries the fitting and which receives it is the first step in reading an assembly drawing.</p><p>Label those two panels on your drawing. Then mark the entry point and the direction of travel. That simple annotation makes it easier to discuss a connection with a designer, machinist, or assembler without relying on a perspective view alone.</p>`},
   {id:'movement',title:'Separate alignment, seating, and sliding',html:`<ol class="guide-steps"><li><b>Align.</b> Bring the fitting into line with the entry region of the receiving feature. Check the relationship of both panels, not only the nearest connector.</li><li><b>Seat.</b> Follow the fitting into the receiving feature. In a visual review, distinguish this approach from the movement that follows.</li><li><b>Slide.</b> Follow the travel into the retained position. Check what else moves with the panel and whether surrounding parts leave that path open.</li></ol><p>The <a href="/how-to/e3259bm/">E3259BM film</a> makes these three movements visible. The homepage model is an interactive explanation of the same relationship; its routed channel is illustrative.</p>`},
   {id:'design-inputs',title:'Bring the right inputs to connector selection',html:`<p>Lockdowel’s product information identifies material and panel thickness as connector-selection considerations. Bring the exact material, thickness, joint location, and intended use to a technical review. Also record whether parts need to be removed later and how the assembler can access them.</p><p>Use the current product drawing for machining dimensions. A web animation, screenshot, or concept model cannot establish bore diameter, routing depth, engagement travel, or a load rating. Those details belong to the selected connector and the reviewed application.</p>`},
   {id:'sample',title:'Review a representative joint before a whole cabinet',html:`<p>A small sample lets your team examine access, panel orientation, and the assembly sequence without handling a complete cabinet. Prepare it using the material and approved machining information intended for the project. Record the connector reference, drawing revision, and any questions raised by the trial.</p><p>Once that joint is understood, review the complete assembly: a movement that works in isolation can become inaccessible after another panel is installed. The <a href="/guides/planning-cabinet-assembly-order/">assembly-order guide</a> provides a way to capture those dependencies.</p>`}
  ],questions:['Which panel carries the fitting?','Where does it enter the receiving panel?','Which direction does the panel travel?','What other parts could obstruct that movement?'],sources:[['Lockdowel product information','https://lockdowel.com/product-list/'],['Lockdowel downloads and product documentation','https://lockdowel.com/downloads/'],['E3259BM demonstration supplied to this project','/how-to/e3259bm/']],product:'Channel lock',cta:'Discuss your connection'
 },
 {
  slug:'e3259bm-assembly-sequence',category:'Connector study',title:'Understanding the E3259BM assembly sequence',description:'Read the E3259BM demonstration step by step: mounting, alignment, seating, and sliding, with questions to take into a technical review.',summary:'Use the connector film and interactive model to understand the movement before reviewing your own application.',image:'video-poster.jpg',imageAlt:'Frame from the supplied E3259BM connector demonstration',reading:'4 minute read',
  sections:[
   {id:'reference',title:'Begin with the connector and the current drawing',html:`<p>The E3259BM study pairs the supplied connector film with a CAD-based presentation on the homepage. The film gives a visual sequence; the model lets you inspect the relationship between the fitting and two panels. Use them to understand the mechanism, then obtain current technical documentation for the exact connector you intend to use.</p><p>Keep the product reference visible in your project brief. Similar-looking fittings should not be treated as interchangeable based on their appearance in an animation.</p>`},
   {id:'mounted-fitting',title:'Identify what moves with the mounting panel',html:`<p>In the interactive demonstration, the connector is mounted to a panel before that panel approaches the receiving channel. Once mounted, the fitting travels with its panel. That relationship is important when reading an exploded view: separated cabinet parts do not imply that every fitting should be loose.</p><p>Pause the <a href="/">interactive connection study</a> at the mounting stage. Identify the carrier panel and note its orientation. The modeled bores and surface detail explain the relationship; obtain actual machining requirements from the product documentation.</p>`},
   {id:'engagement',title:'Watch the engagement as three distinct movements',html:`<p>Open the <a href="/how-to/e3259bm/">original E3259BM film</a> and use its slow-motion or replay controls. First locate the receiving entry, then watch the approach into that entry, followed by the sliding movement. Keeping those movements separate is useful when deciding which part should be held and which part should move in your assembly plan.</p><ol class="guide-steps"><li><b>Before entry:</b> identify the matching fitting and receiving feature.</li><li><b>At entry:</b> observe the relative positions of the panels.</li><li><b>During the slide:</b> look for nearby parts that would need clearance.</li><li><b>At the end:</b> compare the final orientation with the assembly drawing.</li></ol>`},
   {id:'review',title:'Turn the demonstration into a project-specific review',html:`<p>Record the panel material and thickness, the connector location, the intended approach, and the surrounding structure. If a connection cannot follow the demonstrated sequence in your design, take that question into review before treating the animation as an installation procedure.</p><p>The film is a connector demonstration, not approval of its suitability for every cabinet or furniture design. Share a drawing and your intended assembly order with the Lockdowel team so the connector, machining, and access can be reviewed together.</p>`}
  ],questions:['Is E3259BM the selected product reference?','Which panel carries the mounted fitting?','Can the mating panel approach and slide freely?','Which current drawing defines the machining?'],sources:[['Original E3259BM film','/how-to/e3259bm/'],['Interactive E3259BM study','/'],['Lockdowel product documentation','https://lockdowel.com/downloads/']],product:'E3259BM',cta:'Ask about E3259BM'
 },
 {
  slug:'planning-cabinet-assembly-order',category:'Design planning',title:'Planning cabinet assembly order with concealed connectors',description:'Map panel dependencies, entry directions, access, and review points before building a cabinet with concealed connectors.',summary:'Make the order of assembly part of the design, with a simple method for mapping access and panel movement.',image:'open-cubby-exploded.png',imageAlt:'Exploded open-cubby concept drawing with separate panels',reading:'5 minute read',
  sections:[
   {id:'part-map',title:'Create a part map that an assembler can follow',html:`<p>Start from the current drawing and give each panel an unambiguous name or code. Mark front, back, inside, and outside where orientation could be confused. For each joint, identify the fitting carrier and the receiving panel.</p><p>A parts list and an exploded view answer different questions. The list identifies what is present; the view helps explain where it belongs. Neither automatically defines the order of assembly. Add the approach and engagement direction for each connection as a separate part of the plan.</p>`},
   {id:'dependencies',title:'Write down what must happen first',html:`<p>Work through one connection at a time. Ask what has to be installed before it can engage, and what must remain out of the way. A shelf may need access that a later back panel closes. A connector may need sliding travel that an adjacent frame would obstruct. Treat these as design questions to verify on your own geometry, not universal assembly rules.</p><p>For each stage, record four items: the part being added, the supporting structure already present, the movement required, and the condition that confirms the stage is complete. This gives your reviewer a sequence to evaluate rather than a set of isolated views.</p>`},
   {id:'access',title:'Check access through the complete sequence',html:`<p>Review the entry and travel path at the stage when a joint is actually assembled. Include installed panels, frames, shelves, and nearby fittings in that review. Also consider how the assembly is supported and whether a part must be held or repositioned.</p><p>The <a href="/drawings/open-cubby/">open-cubby concept</a> is a useful visual starting point for discussing panels and connections. It is a concept study, so its geometry and dimensions should not be transferred into a production file.</p><p>If later removal matters, review the reverse sequence as well. Identify which parts must come off first and whether their access will still exist in the installed setting.</p>`},
   {id:'trial',title:'Record the trial and the drawing revision together',html:`<p>Run a representative trial only after the hardware and machining details have been reviewed. Record the material, connector reference, drawing revision, panel order, and any point that requires clarification. Keep observations separate from proposed fixes so a note does not accidentally become a manufacturing instruction.</p><p>If you compare assembly time, define the start and finish of the task consistently and record the conditions. The <a href="/savings/">assembly labor calculator</a> can then turn your measured times into a scenario. Its result covers labor only; it does not include hardware, machining, equipment, shipping, or training costs.</p>`},
   {id:'handoff',title:'Give the reviewer a focused handoff',html:`<p>Bring the drawing, the proposed sequence, and the specific uncertainty. For example: “After the back is installed, can this shelf still complete its engagement travel?” A precise question is more useful than asking whether the complete cabinet looks right.</p><p>The project brief below captures the application, material, volume, and review question so the conversation can begin with the design already in context.</p>`}
  ],questions:['Are all panels named and oriented?','Does every connection have an entry and travel direction?','Are support and access checked at each stage?','Are unresolved observations separate from approved revisions?'],sources:[['Lockdowel cabinetry applications','https://lockdowel.com/cabinetry/'],['Lockdowel construction processes','https://lockdowel.com/construction-methods-2/'],['Open-cubby concept study','/drawings/open-cubby/']],product:'Cabinet assembly',cta:'Review your assembly plan'
 }
];
const escape=(s)=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export function guidePage(g){const route=`/guides/${g.slug}/`;return {path:route,title:`${g.title} | Lockdowel Build`,description:g.description,guide:g,body:`<section class="guide-heading wrap"><a class="back-link" href="/guides/">← All technical guides</a><p class="eyebrow">${g.category.toUpperCase()}</p><h1>${g.title}</h1><p class="guide-summary">${g.summary}</p><div class="guide-meta"><span>LOCKDOWEL BUILD</span><span>${g.reading}</span><span>Updated October 4, 2026</span></div></section><div class="guide-layout wrap"><aside class="guide-toc"><p class="eyebrow">IN THIS GUIDE</p><nav aria-label="Guide contents">${g.sections.map(s=>`<a href="#${s.id}">${s.title}</a>`).join('')}</nav><a class="text-link" href="/start-project/?source=${encodeURIComponent(route)}&amp;product=${encodeURIComponent(g.product)}">${g.cta} ↗</a></aside><article class="guide-article"><figure class="guide-figure"><img src="/assets/${g.image}" alt="${escape(g.imageAlt)}" width="960" height="600"><figcaption>${escape(g.imageAlt)}. Visual reference; use current product documentation for manufacturing details.</figcaption></figure>${g.sections.map(s=>`<section id="${s.id}"><h2>${s.title}</h2>${s.html}</section>`).join('')}<section class="guide-review"><p class="eyebrow">TAKE INTO YOUR REVIEW</p><h2>Four questions to bring with you.</h2><ul>${g.questions.map(q=>`<li>${q}</li>`).join('')}</ul><a class="button" href="/start-project/?source=${encodeURIComponent(route)}&amp;product=${encodeURIComponent(g.product)}">${g.cta} ↗</a></section><section class="guide-sources"><h2>Sources and further reading</h2><ul>${g.sources.map(([label,url])=>`<li><a href="${url}">${label} ↗</a></li>`).join('')}</ul><p>This guide explains the referenced material and offers planning questions. Product selection, machining dimensions, and application suitability require current technical documentation and project-specific review.</p></section></article></div><section class="guide-related wrap"><p class="eyebrow">KEEP BUILDING YOUR UNDERSTANDING</p><h2>Next in the library.</h2>${guides.filter(x=>x!==g).map(x=>`<a href="/guides/${x.slug}/"><span>${x.category}</span><strong>${x.title}</strong><b aria-hidden="true">↗</b></a>`).join('')}</section>`};}
export const guideIndex={path:'/guides/',title:'Lockdowel assembly and connector guides | Lockdowel Build',description:'Learn how channel-lock connections work, follow the E3259BM sequence, and plan cabinet assembly order with practical technical guides.',body:`<section class="guide-heading wrap"><p class="eyebrow">THE TECHNICAL LIBRARY</p><h1>Understand the connection.<br>Plan the next move.</h1><p class="guide-summary">Practical guides for the questions between an idea and an assembly. Start with the mechanism, follow a connector, or work through your cabinet sequence.</p></section><section class="guide-index wrap" aria-label="Technical guides">${guides.map((g,i)=>`<article><a class="guide-index-image" href="/guides/${g.slug}/"><img src="/assets/${g.image}" alt="${escape(g.imageAlt)}" width="640" height="400" ${i?'loading="lazy"':''}></a><div><p class="eyebrow">0${i+1} / ${g.category.toUpperCase()}</p><h2><a href="/guides/${g.slug}/">${g.title}</a></h2><p>${g.summary}</p><a class="text-link" href="/guides/${g.slug}/">Read the guide ↗</a></div></article>`).join('')}</section><section class="guide-next wrap"><div><p class="eyebrow">PUT THE GUIDE TO WORK</p><h2>Bring your drawing.<br>Bring your questions.</h2><p>Turn what you have learned into a project-specific conversation.</p></div><a class="button" href="/start-project/?source=%2Fguides%2F">Start a project inquiry ↗</a></section>`};
export const guidePages=[guideIndex,...guides.map(guidePage)];
