import { drawings, project } from '../content/projects.mjs';
export const arrow = '<span aria-hidden="true">↗</span>';
const link = (url,label,cls='button') => `<a class="${cls}" href="${url}">${label}${arrow}</a>`;
const tag = (text) => `<p class="eyebrow"><span class="dot"></span>${text}</p>`;
export function scene(id='assembly',compact=false) {
 return `<div class="scene ${compact?'scene-compact':''}" data-scene id="${id}">
 <div class="scene-top"><span>CONNECTION STUDY / 001</span><span class="live-indicator">INTERACTIVE 3D</span></div>
 <div class="scene-canvas" role="img" aria-label="Interactive conceptual boat table with four wood panels and eight neon-green connectors. Use the controls below to assemble or explode the parts."><img class="scene-fallback" src="/assets/boat-table-exploded.png" alt="Exploded boat table from the Lockdowel concept drawing" width="1191" height="842"></div>
 <div class="scene-callout"><span class="crosshair">+</span><div>THE CONNECTION<br><b>Changes everything.</b></div></div>
 <div class="scene-bottom"><span class="scene-hint">DRAG TO ROTATE</span><div class="scene-controls" aria-label="Assembly model controls"><button type="button" data-state="assembled" aria-pressed="false">Assembled</button><button type="button" data-state="exploded" aria-pressed="true">Exploded</button><button type="button" data-scene-play aria-label="Play assembly overview">▶</button><button type="button" data-scene-reset aria-label="Reset model view">↺</button></div></div>
 <p class="scene-note">Concept geometry · connectors simplified and highlighted · not manufacturing instructions</p>
 </div>`;
}
function drawingCard(d) { return `<article class="drawing-card" data-kind="${d.kind}"><a class="drawing-image" href="/assets/${d.slug}-drawing.pdf" target="_blank" rel="noopener"><img src="/assets/${d.slug}-exploded.png" width="1191" height="842" alt="${d.title}: exploded parts and connector locations" loading="lazy"><span>${d.pages} SHEETS ${arrow}</span></a><div class="drawing-info"><p class="eyebrow">${d.code} / REV A</p><h3>${d.title}</h3><p>${d.description}</p><div class="drawing-stats"><span>${d.parts} parts</span><span>${d.locks} connections</span></div>${link(`/assets/${d.slug}-drawing.pdf`,'Open drawing','text-link')}</div></article>`; }
const cta = () => `<section class="end-cta wrap"><p class="eyebrow">FROM POSSIBILITY TO PRODUCTION</p><h2>Let’s build<br>what’s next<span>.</span></h2><div><p>Bring your idea to the Lockdowel team.<br>Let’s find the right connection for it.</p>${link('https://lockdowel.com/contact/','Start a conversation')}${link('https://lockdowel.com/evaluation-kits/','Explore evaluation kits','text-link')}</div></section>`;
export const pages = [
{
 path:'/', title:'Build with Lockdowel | Explore the next connection', description:'Explore Lockdowel through interactive assembly studies, technical drawings and connector demonstrations. See how your next furniture or cabinet project could come together.',
 body:`<section class="hero wrap"><div class="hero-copy">${tag('THE LOCKDOWEL BUILD STUDIO')}<h1>MAKE<br>THE NEXT<br><span>CONNECTION.</span></h1><p>Big ideas. Invisible connections.<br>A whole new way to see what you can build.</p><div class="hero-actions">${link('/explore/','Explore the possibilities')}${link('/how-to/e3259bm/','Watch it connect','text-link')}</div><div class="hero-index"><span>01 / EXPLORE</span><span>02 / UNDERSTAND</span><span>03 / BUILD</span></div></div>${scene()}</section>
 <div class="ticker" aria-hidden="true"><div>LESS IN THE WAY. MORE POSSIBILITY. <span>↗</span> ALIGN. SEAT. SLIDE. <span>↗</span> MAKE THE CONNECTION. <span>↗</span> LESS IN THE WAY. MORE POSSIBILITY. <span>↗</span></div></div>
 <section class="intro wrap reveal"><p class="eyebrow">HIDDEN HARDWARE. VISIBLE POSSIBILITIES.</p><div class="intro-grid"><h2>The smallest detail.<br>The biggest shift.</h2><div><p>Great design deserves a connection that stays out of sight. Lockdowel’s concealed fasteners bring furniture, cabinetry, and architectural panels together.</p><p>This is where you can get closer. Explore a construction concept, step through a connector film, and put the drawing beside the idea.</p>${link('https://lockdowel.com/product-list/','Meet the Lockdowel systems','text-link')}</div></div></section>
 <section class="feature-film wrap reveal"><a class="film-cover" href="/how-to/e3259bm/"><img src="/assets/video-poster.jpg" alt="E3259BM connector assembly demonstration" width="1280" height="720" loading="lazy"><span class="film-play" aria-hidden="true">▶</span><span class="film-caption">E3259BM / THE CONNECTION IN MOTION <b>00:40 ↗</b></span></a><div class="film-copy"><p class="eyebrow">A CLOSER LOOK / 001</p><h2>Align.<br>Seat.<br><span>Slide.</span></h2><p>Get inside the connection. A focused, 40-second view of the E3259BM mechanism, with controls to explore at your own pace.</p>${link('/how-to/e3259bm/','Watch the how-to','text-link')}</div></section>
 <section class="drawing-section wrap reveal"><div class="section-head"><div><p class="eyebrow">FROM THE DRAWING BOARD</p><h2>Ideas, taken apart.</h2></div>${link('/drawings/','Explore the drawings','text-link')}</div><div class="drawing-grid">${drawings.map(drawingCard).join('')}</div></section>
 <section class="project-banner reveal"><div class="wrap project-banner-inner"><div><p class="eyebrow">ONE PROJECT. ONE PLACE.</p><h2>Your drawing.<br>Your story.<br><em>One connection.</em></h2><p>A focused presentation page brings the concept, drawing, and next steps together. Made for a real conversation about what comes next.</p>${link('/projects/boat-table/','Open the sample project')}</div><a class="project-peek" href="/projects/boat-table/"><span class="eyebrow">PROJECT 001 <b>↗</b></span><img src="/assets/boat-table-sheet.png" alt="Boat table project drawing preview" width="1191" height="842" loading="lazy"><span>BOAT TABLE <small>CONNECTION STUDY / REV A</small></span></a></div></section>
 ${cta()}`
},
{
 path:'/explore/',title:'Explore Lockdowel applications | Build studio',description:'Start with furniture, cabinetry or wall panels. Explore a Lockdowel application, a concept drawing and the questions to take into a technical review.',
 body:`<section class="page-intro wrap">${tag('FIND YOUR STARTING POINT')}<h1>What are<br>you <span>building?</span></h1><p>Start with the application. Get closer to the right conversation.</p></section><section class="explorer wrap" data-explorer><div class="application-tabs" role="tablist" aria-label="Application"><button role="tab" id="tab-furniture" aria-controls="application-panel" aria-selected="true" data-application="furniture">01 <b>Furniture</b> ↗</button><button role="tab" id="tab-cabinetry" aria-controls="application-panel" aria-selected="false" tabindex="-1" data-application="cabinetry">02 <b>Cabinetry</b> ↗</button><button role="tab" id="tab-panels" aria-controls="application-panel" aria-selected="false" tabindex="-1" data-application="panels">03 <b>Wall panels</b> ↗</button></div><div id="application-panel" class="application-panel" role="tabpanel" aria-labelledby="tab-furniture" tabindex="0"><img id="application-image" src="/assets/furniture.jpg" alt="Furniture application from Lockdowel’s main website" width="768" height="476"><div><p class="eyebrow" id="application-label">FURNITURE / BUILT AROUND YOUR IDEA</p><h2 id="application-title">Let the design<br>do the talking.</h2><p id="application-description">Explore concealed connections for tables, casegoods and other furniture. Start with access, assembly direction and the material your design uses.</p><ul id="application-questions" class="check-list"><li>Where can each part approach and slide?</li><li>Will the finished piece need to come apart?</li><li>What material and panel thickness are you using?</li></ul><a id="application-link" href="https://lockdowel.com/furniture/" class="button">Explore furniture on Lockdowel.com ${arrow}</a></div></div><p class="fine-print">Application guidance is a starting point. Confirm the connector, material, machining and assembly path with Lockdowel for your design.</p></section><section class="wrap drawing-section"><div class="section-head"><div><p class="eyebrow">SEE AN IDEA COME TOGETHER</p><h2>From concept to conversation.</h2></div></div><div class="two-up"><a class="resource-tile" href="/projects/boat-table/"><span>01 / PROJECT PRESENTATION</span><h3>Walk through<br>the boat table.</h3><p>Drawing, interactive model, and review notes.</p><b>Open the study ↗</b></a><a class="resource-tile lime-tile" href="/savings/"><span>02 / ASSEMBLY SCENARIO</span><h3>What could<br>time be worth?</h3><p>Explore your own volume and labor assumptions.</p><b>Try the calculator ↗</b></a></div></section>${cta()}`
},
{
 path:'/drawings/',title:'Lockdowel concept drawings | Build studio',description:'Explore three Lockdowel demonstration drawings: a boat table, an open cubby and an angled table. Download the original concept PDFs and view their connector studies.',
 body:`<section class="page-intro wrap">${tag('THE DRAWING LIBRARY')}<h1>Every connection<br>starts with <span>an idea.</span></h1><p>Three concepts. The drawings behind them. Open one up and follow the connections.</p></section><section class="wrap drawing-section"><div class="filter-bar" role="group" aria-label="Filter drawings"><button data-filter="All" aria-pressed="true">All drawings <span>03</span></button><button data-filter="Furniture" aria-pressed="false">Furniture <span>02</span></button><button data-filter="Cabinetry" aria-pressed="false">Cabinetry <span>01</span></button><p>PDF / CONCEPT STUDIES</p></div><div class="drawing-grid">${drawings.map(drawingCard).join('')}</div><p class="notice">These supplied drawings are concept demonstrations, not CNC or production instructions. They include conceptual hardware geometry. Confirm the relevant product specifications and manufacturing details with Lockdowel.</p></section><section class="wrap editorial"><p class="eyebrow">MAKE THE DRAWING PART OF THE STORY</p><h2>A document can explain a part.<br>A project page can connect the dots.</h2><p>Put the drawing beside a visual overview and the questions that matter. The sample project shows how a hand-authored presentation can give your next conversation a clear starting point.</p>${link('/projects/boat-table/','See the sample presentation')}</section>${cta()}`
},
{
 path:'/how-to/e3259bm/', title:'E3259BM: Align, seat, slide | Lockdowel connector demonstration', description:'Watch the supplied 40-second Lockdowel E3259BM connector demonstration. Use video playback, frame review and the written overview to examine the connection.',
 body:`<section class="page-intro wrap compact-intro">${tag('IN MOTION / E3259BM')}<h1>Small movement.<br><span>Big connection.</span></h1><p>Align. Seat. Slide. Take a closer look at the E3259BM connection.</p></section><section class="video-study wrap"><video id="howto-video" controls playsinline preload="metadata" poster="/assets/video-poster.jpg" aria-label="40-second E3259BM align, seat and slide demonstration"><source src="/assets/e3259bm-align-seat-slide.mp4" type="video/mp4">Your browser does not support embedded video. <a href="/assets/e3259bm-align-seat-slide.mp4">Open the video.</a></video><div class="video-toolbar"><div><span class="dot"></span><span>ORIGINAL DEMONSTRATION / 1080P / 00:40</span></div><div><button type="button" data-video-back>−5 seconds</button><button type="button" data-video-speed aria-pressed="false">0.5× slow motion</button><button type="button" data-video-restart>↺ Restart</button></div></div><div class="sequence"><article><span>01</span><h2>Align.</h2><p>Bring the mating parts into the relationship shown in the film. The path into the connection matters.</p></article><article><span>02</span><h2>Seat.</h2><p>Observe the fitting entering the receiving feature before the locking movement begins.</p></article><article><span>03</span><h2>Slide.</h2><p>Follow the change in movement as the parts reach their connected position.</p></article></div><p class="notice">Visual overview of the supplied film. Use the current E3259BM product documentation and Lockdowel’s guidance for installation, tolerances and suitability. No dimensions or load ratings are inferred from the animation.</p></section><section class="wrap editorial"><p class="eyebrow">KEEP EXPLORING</p><h2>See the product.<br>Ask the right questions.</h2><p>The main Lockdowel website is the place to explore the product range, talk to the team, and take the next step toward evaluating a connection in your own shop.</p><div class="button-row">${link('https://lockdowel.com/product-list/','Explore the products')}${link('https://lockdowel.com/contact/','Ask about E3259BM','text-link')}</div></section>`
},
{
 path:'/projects/boat-table/',title:'Boat table connection study | Lockdowel project presentation',description:'A sample Lockdowel project presentation bringing together a boat table concept, source drawing, interactive assembly overview and technical review notes.',private:true,
 body:`<section class="project-title wrap"><a class="back-link" href="/drawings/">← BACK TO THE DRAWINGS</a><div class="project-meta"><span>DEMONSTRATION PROJECT / 001</span><span>${project.reference} · REV ${project.revision}</span><button type="button" data-copy-link>Copy page link ↗</button></div><h1>${project.title}</h1><p>${project.summary}</p></section><section class="wrap project-model">${scene('project-assembly',true)}<div class="project-facts"><div><span>THE CONCEPT</span><b>Boat table</b></div><div><span>THE STRUCTURE</span><b>04 panels</b></div><div><span>THE CONNECTIONS</span><b>08 locks</b></div><div><span>THE ENVELOPE</span><b>1200 × 720 × 600 mm</b></div></div></section><section class="wrap project-detail"><div><p class="eyebrow">01 / THE SOURCE DRAWING</p><h2>See what’s<br>behind the idea.</h2><p>Six sheets bring the part schedule, connection locations, and conceptual assembly movements together.</p>${link('/assets/boat-table-drawing.pdf','Open the complete drawing')}<p class="fine-print">Concept demonstration · Rev A · Units: mm<br>Not production or CNC instructions.</p></div><a class="project-drawing" href="/assets/boat-table-drawing.pdf"><img src="/assets/boat-table-sheet.png" alt="Original boat table concept sheet with overall envelope and component schedule" width="1191" height="842" loading="lazy"></a></section><section class="wrap review-notes"><p class="eyebrow">02 / WHAT TO REVIEW TOGETHER</p><h2>The details make the difference.</h2><ol>${project.notes.map(n=>`<li>${n}</li>`).join('')}</ol></section><section class="wrap project-detail"><a class="film-cover" href="/how-to/e3259bm/"><img src="/assets/video-poster.jpg" alt="Separate E3259BM mechanism demonstration" width="1280" height="720" loading="lazy"><span class="film-play" aria-hidden="true">▶</span></a><div><p class="eyebrow">03 / A SEPARATE MECHANISM EXAMPLE</p><h2>A connection<br>in motion.</h2><p>The E3259BM film offers a closer look at an align, seat, and slide sequence. It is a separate example, not an assembly instruction for this table.</p>${link('/how-to/e3259bm/','Watch the connector film','text-link')}</div></section><section class="wrap next-step"><p class="eyebrow">04 / THE NEXT CONVERSATION</p><h2>Make it specific<br>to your project.</h2><p>Confirm materials, hardware, machining, assembly access, and the requirements of the finished product with the Lockdowel team.</p>${link('https://lockdowel.com/contact/','Discuss a project')}<p class="fine-print">This is a sample presentation using supplied concept drawings. No client approval or engineering validation is implied.</p></section><div class="toast" role="status" aria-live="polite"></div>`
},
{
 path:'/savings/',title:'Assembly labor scenario calculator | Lockdowel Build',description:'Estimate the value of assembly time with your own production volume, labor rate and measured before-and-after cycle times. Transparent assumptions and downloadable results.',
 body:`<section class="page-intro wrap">${tag('PUT YOUR NUMBERS TO WORK')}<h1>What could<br><span>time be worth?</span></h1><p>Explore an assembly labor scenario with your own numbers. No promised savings. Just clear assumptions.</p></section><section class="calculator wrap" data-calculator><form id="savings-form"><p class="eyebrow">YOUR SCENARIO</p><label for="units">Units assembled per month</label><div class="input-unit"><input id="units" name="units" type="number" min="0" max="10000000" step="1" value="500" required><span>units</span></div><label for="before">Current assembly time per unit</label><div class="input-unit"><input id="before" name="before" type="number" min="0" max="100000" step="0.1" value="20" required><span>minutes</span></div><label for="after">Trial assembly time per unit</label><div class="input-unit"><input id="after" name="after" type="number" min="0" max="100000" step="0.1" value="12" required><span>minutes</span></div><label for="rate">Loaded labor rate</label><div class="input-unit"><input id="rate" name="rate" type="number" min="0" max="100000" step="0.01" value="35" required><span>USD / hour</span></div><p class="fine-print">Starting values are illustrative. Replace them with measured times and your own labor costs.</p></form><div class="calculator-result"><p class="eyebrow">ESTIMATED MONTHLY LABOR DIFFERENCE</p><output id="savings-money" for="units before after rate">$2,333</output><p id="savings-direction">Less assembly labor in this scenario.</p><div class="result-stats"><div><b id="savings-hours">66.7</b><span>hours / month</span></div><div><b id="savings-percent">40%</b><span>cycle time reduction</span></div></div><div class="comparison-bars"><div><span>CURRENT</span><i id="bar-before"></i></div><div><span>TRIAL</span><i id="bar-after"></i></div></div><p id="calculator-error" role="status"></p><button class="button dark-button" type="button" data-export-savings>Download scenario ↓</button></div></section><section class="wrap assumptions"><h2>What’s included?</h2><p>Monthly labor difference = units × (current minutes − trial minutes) ÷ 60 × hourly labor rate. A negative result means the trial takes longer or costs more in assembly labor.</p><p>This is a labor scenario, not a full return-on-investment model. It excludes connectors, machining, equipment, training, overhead changes, shipping and other costs. Measure a representative trial before making a decision.</p>${link('https://lockdowel.com/evaluation-kits/','Start with an evaluation kit','text-link')}</section>`
}
];
export function shell(page,production=false) {
 const domain='https://build.lockdowel.com';
 const noindex=!production||page.private;
 const schema = {'@context':'https://schema.org','@type':'WebPage',name:page.title,description:page.description,url:domain+page.path,isPartOf:{'@type':'WebSite',name:'Lockdowel Build',url:domain},about:{'@type':'Organization',name:'Lockdowel',url:'https://lockdowel.com'}};
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><meta name="robots" content="${noindex?'noindex, nofollow':'index, follow'}"><link rel="canonical" href="${domain+page.path}"><meta property="og:type" content="website"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${domain+page.path}"><meta property="og:image" content="${domain}/assets/video-poster.jpg"><meta name="theme-color" content="#111411"><link rel="icon" href="/assets/favicon.png"><link rel="preload" href="/assets/geist.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${JSON.stringify(schema)}</script><script type="module" src="/app.js"></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Lockdowel Build home"><span class="brand-logo"><img src="/assets/lockdowel-logo.png" alt="Lockdowel" width="180" height="60"></span><span class="brand-divider"></span><span class="brand-build">BUILD<span>THE CONNECTION STUDIO</span></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menu +</button><nav id="main-nav" aria-label="Main navigation"><a href="/explore/" ${page.path==='/explore/'?'aria-current="page"':''}>Explore</a><a href="/drawings/" ${page.path==='/drawings/'?'aria-current="page"':''}>Drawings</a><a href="/how-to/e3259bm/" ${page.path.includes('/how-to/')?'aria-current="page"':''}>How it works</a><a class="store-link" href="https://lockdowel.com/elementor-37341/">Online Store ${arrow}</a></nav></header><main id="main">${page.body}</main><footer class="site-footer wrap"><div><a href="https://lockdowel.com/" class="footer-brand">LOCKDOWEL<span>®</span></a><p>Better connections. New possibilities.</p></div><div class="footer-links"><a href="https://lockdowel.com/">Main website ↗</a><a href="https://lockdowel.com/contact/">Contact ↗</a><a href="https://lockdowel.com/product-list/">Products ↗</a><a href="/savings/">Assembly calculator</a></div><div class="footer-bottom"><span>LOCKDOWEL BUILD / LOCAL CONCEPT PREVIEW</span><button type="button" data-motion aria-pressed="false">Pause motion</button><span>DESIGNED TO CONNECT.</span></div></footer><noscript><div class="noscript">Interactive models and tools need JavaScript. All drawings, page content and the video remain available.</div></noscript></body></html>`;
}
